### ISSUE TITLE
package fails to build from github due to error in DESCRIPTION

### ISSUE THREAD

**Issue by rpruim** [zhartsuff/Data303RPackage#12]
Here's the message:

```
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘/private/var/folders/k4/_r3b2rqx21qd6chjp04k7pnc0000gp/T/RtmppcGV71/remotes1038584985d8/zhartsuff-Data303RPackage-5d658c3/DESCRIPTION’ ... OK
* preparing ‘newprojdata303’:
* checking DESCRIPTION meta-information ... ERROR
Malformed maintainer field.
```

**Comment by rpruim** [comment]
You cannot have more than one "creator".  That's actually a misnomer -- it is really the maintainer, and that must be a uniquely identified person.

> One or more three letter codes specifying the role. These are the most important roles to know about:
>
> * cre: the creator or maintainer, the person you should bother if you have problems. Despite being short for “creator”, this is the correct role to use for the current maintainer, even if they are not the initial creator of the package.
>
> * aut: authors, those who have made significant contributions to the package.
>
> * ctb: contributors, those who have made smaller contributions, like patches.
>
> * cph: copyright holder. This is used to list additional copyright holders who are not authors, typically companies, like an employer of one or more of the authors.
>
> * fnd: funder, the people or organizations that have provided financial support for the development of the package.

See https://r-pkgs.org/description.html#author-who-are-you for details.

**Comment by gef4** [comment]
We changed the the descirptions to be a vector and added our full emails.
