### ISSUE TITLE
Bug in df_apply()?

### ISSUE THREAD

**Issue by rpruim** [zhartsuff/Data303RPackage#20]
I'm seeing

```r
df_apply(mosaicData::KidsFeet, .fun = round, 
            .filter = function(x) { is.numeric(x) && (mean(x) > 10)},
            digits = -1) |> 
  head()

    name birthmonth birthyear length width sex biggerfoot domhand
1  David          5        88     24   8.4   B          L       R
2   Lars         10        87     25   8.8   B          L       L
3   Zach         12        87     24   9.7   B          R       R
4   Josh          1        88     25   9.8   B          L       R
5   Lang          2        88     25   8.9   B          L       R
6 Scotty          3        88     26   9.7   B          R  
```
This should round columns with large values to the nearest 10.  I'm wondering if you are not actually passing `...` through to `.fun()`.

Do you have a test for this?  Does it pass?

**Comment by garcie** [comment]
I think we missed the point of "..."
It's now returning this:
  name birthmonth birthyear length width sex biggerfoot domhand
1  David          5        90     20   8.4   B          L       R
2   Lars         10        90     30   8.8   B          L       L
3   Zach         12        90     20   9.7   B          R       R
4   Josh          1        90     30   9.8   B          L       R
5   Lang          2        90     30   8.9   B          L       R
6 Scotty          3        90     30   9.7   B          R       R

which I think is what you want

**Comment by garcie** [comment]
(Not sure how to format it nicely.) 

Anyway, I will add a similar example to the test cases.

**Comment by garcie** [comment]
Should all be addressed but I'll wait for you to confirm/

**Comment by rpruim** [comment]
For github markdown fomratting, see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github

You can format R code by typing

````
```r
````
before your code and 

````
```
````
after.  Leave off the r for computer output.

And even nicer way to deal with R code and output is to use the {reprex} package which is designed for just this sort of thing. (See https://reprex.tidyverse.org/.)
