### ISSUE TITLE
Document df_apply()

### ISSUE THREAD

**Issue by rpruim** [zhartsuff/Data303RPackage#25]
Have you documented `df_apply()`?  Does the documentation have examples? 

I'm getting 

```
Warning in example(df_apply, package = projects[params$index, "package"]): no
help found for 'df_apply'
```

[round1-4.pdf](https://github.com/zhartsuff/Data303RPackage/files/11073966/round1-4.pdf)

**Comment by rpruim** [comment]
Be sure to `@export` as well.

**Comment by garcie** [comment]
Just documented and it's working but what do you mean by @export?

**Comment by rpruim** [comment]
For functions to be available to users of your package, they must be exported.  You can signal this using 

```
#` @export
```
In the roxygen documentation.

See https://roxygen2.r-lib.org/articles/namespace.html

(You can ignore all the stuff about S3, S4, R6, etc.)

**Comment by garcie** [comment]
Done thanks!
